import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "../global.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ThemeProvider } from "next-themes";
import Provider from "./Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Anime Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} container mx-auto`}
      >
    <Provider>
        <Navbar />
        {children}
        <Footer/>
        </Provider>
      </body>
    </html>
  );
}
